import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useScrollAnimation } from '@/hooks/useScrollAnimation';
import { Shield, Users, Award, Clock } from 'lucide-react';
export function AboutUs() {
    const containerRef = useScrollAnimation();
    return (_jsxs("section", { id: "about", ref: containerRef, className: "relative py-20 md:py-32 bg-tech-navy overflow-hidden", children: [_jsx("div", { className: "absolute top-0 left-0 w-1/2 h-full bg-eco-primary/5 blur-3xl" }), _jsx("div", { className: "relative z-10 w-full px-4 sm:px-6 lg:px-8 xl:px-12", children: _jsx("div", { className: "max-w-7xl mx-auto", children: _jsxs("div", { className: "grid lg:grid-cols-2 gap-12 lg:gap-20 items-center", children: [_jsxs("div", { "data-animate": "fade-up", children: [_jsx("span", { className: "text-eco-primary font-semibold text-sm uppercase tracking-wider", children: "About Us" }), _jsxs("h2", { className: "mt-4 text-3xl md:text-4xl lg:text-5xl font-bold text-white", children: ["South Florida's Most ", _jsx("span", { className: "text-eco-primary", children: "Trusted" }), " Mold Experts"] }), _jsx("p", { className: "mt-6 text-white/70 text-lg leading-relaxed", children: "For over 15 years, AA Mold Hunters has protected South Florida homes from the hidden dangers of mold and water damage. Our certified technicians combine cutting-edge technology with proven remediation techniques to deliver results that exceed expectations." }), _jsx("p", { className: "mt-4 text-white/70 text-lg leading-relaxed", children: "We understand that mold isn't just an eyesore\u2014it's a health hazard that can compromise your family's wellbeing. That's why we respond faster, inspect thoroughness, and remediate completely." }), _jsx("div", { className: "mt-8 grid grid-cols-2 gap-6", children: [
                                            { icon: Shield, number: '15+', label: 'Years Experience' },
                                            { icon: Users, number: '5,000+', label: 'Homes Protected' },
                                            { icon: Award, number: '100%', label: 'Satisfaction Rate' },
                                            { icon: Clock, number: '24/7', label: 'Emergency Response' },
                                        ].map((stat, i) => (_jsxs("div", { className: "flex items-center gap-4", children: [_jsx("div", { className: "w-14 h-14 rounded-xl bg-eco-primary/20 flex items-center justify-center", children: _jsx(stat.icon, { className: "w-7 h-7 text-eco-primary" }) }), _jsxs("div", { children: [_jsx("div", { className: "text-2xl font-bold text-white", children: stat.number }), _jsx("div", { className: "text-white/60 text-sm", children: stat.label })] })] }, i))) })] }), _jsxs("div", { className: "relative", "data-animate": "slide-right", children: [_jsxs("div", { className: "relative rounded-2xl overflow-hidden", children: [_jsx("img", { src: "/images/team.jpg", alt: "AA Mold Hunters Team", className: "w-full h-[500px] object-cover" }), _jsx("div", { className: "absolute inset-0 bg-gradient-to-t from-tech-navy/80 to-transparent" })] }), _jsx("div", { className: "absolute -bottom-6 -left-6 glass-card p-6 rounded-xl", children: _jsxs("div", { className: "flex items-center gap-4", children: [_jsx("div", { className: "w-16 h-16 rounded-full bg-eco-primary flex items-center justify-center", children: _jsx(Shield, { className: "w-8 h-8 text-white" }) }), _jsxs("div", { children: [_jsx("div", { className: "text-white font-bold text-lg", children: "Licensed & Insured" }), _jsx("div", { className: "text-white/60 text-sm", children: "FL License #Mold-12345" })] })] }) })] })] }) }) })] }));
}
//# sourceMappingURL=AboutUs.js.map